#example response:
#[
#  {
#    "firstName": "testImie",
#    "lastName": "testNazwisko",
#    "email": "testEmail@localhost.com",
#    "password": "test",
#    "repeatPassword": "test",
#    "birthDate": "2023-09-20T22:00:00.000Z",
#    "gender": "Nieznana",
#    "id": 8
#  }
#]


### find All
GET http://localhost:5000/api/accounts
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==

### find by Id
GET http://localhost:5000/api/accounts/4
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==

### find by Email
GET http://localhost:5000/api/accounts/?email=jan.nowak2@gmail.com
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==


### create
POST http://localhost:5000/api/accounts
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==
Content-Type: application/json

{
  "firstName": "testImie",
  "lastName": "testNazwisko",
  "email": "testiiii12346667891260@wp.pl",
  "password": "test",
  "repeatPassword": "test",
  "birthDate": "2023-09-20T22:00:00.000Z",
  "gender": "Nieznana"
}


### update
PUT http://localhost:5000/api/accounts/5
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==
Content-Type: application/json

{
  "firstName": "testImie",
  "lastName": "testNazwisko",
  "email": "jan.nowak@gmail.com",
  "password": "test",
  "repeatPassword": "test",
  "birthDate": "2023-09-20T22:00:00.000Z",
  "gender": "Nieznana",
  "id": 500
}


### delete
DELETE http://localhost:5000/api/accounts/1
Authorization: Basic amFuLm5vd2FrQGdtYWlsLmNvbTphZG1pbg==
Content-Type: application/json
