#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/newman/bin/new,an.js" "$0"
  ret=$?
else
  node "$basedir/node_modules/newman/bin/newman.js" "$0"
  ret=$?
fi
exit $ret
